config/routes.rb
Rails.application.routes.draw do
  get 'reports/index' => 'reports#index', as: :reports

  get 'reports/employee_on_vehicle/:id' => 'reports#employee_on_vehicle', as: :employee_on_vehicle

  get 'reports/vehicle_workshop/:id' => 'reports#vehicle_workshop', as: :vehicle_workshop

  get 'reports/vehicle_spare_parts/:id' => 'reports#vehicle_spare_parts', as: :vehicle_spare_parts

  get 'reports/vehicle_procedures/:id' => 'reports#vehicle_procedures', as: :vehicle_procedures

  resources :order_vehicle_workshops

  get 'finance/summary' => 'finance#summary', as: :finance

  resources :employees

  resources :workshops

  resources :fiscal_data

  resources :clients

  resources :locations

  resources :spare_parts

  resources :labors

  resources :vehicles

  resources :orders

  resources :procedures

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :vehicles, inverse_of: :client
  belongs_to :location, inverse_of: :client

	validates :first_name, presence: true
	validates :last_name, presence: true

  def full_name
    first_name + " " + last_name + " - Vehiculos: " + vehicles.count.to_s 
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders, inverse_of: :employee
  has_many :labors, inverse_of: :employee

	validates :name, presence: true
	validates :last_name, presence: true
	validates :salary, presence: true

	def full_name
		name + " " + last_name + " - Trabajos: " + orders.count.to_s 
	end

  def full_name_only
    name + " " + middle_name + " " + last_name
  end
end

app/models/fiscal_datum.rb
class FiscalDatum < ActiveRecord::Base
  belongs_to :location, inverse_of: :fiscal_data

	validates :RFC, presence: true
	validates :entity_name, presence: true
	validates :date_of_birth, presence: true

end

app/models/labor.rb
class Labor < ActiveRecord::Base
  belongs_to :employee, inverse_of: :labors
  belongs_to :procedure, inverse_of: :labors

	validates :cost, presence: true
	validates :estimated_time, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :client, inverse_of: :location
  has_one :fiscal_data, inverse_of: :location
  
	validates :street, presence: true
	validates :street_number, presence: true
	validates :suburb, presence: true
	validates :postal_code, presence: true

  def full_address
    street + " " + street_number.to_s + ", " + suburb + " " + postal_code.to_s
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :procedures, inverse_of: :order
  has_many :order_vehicle_workshops, inverse_of: :order
  belongs_to :employee, inverse_of: :orders

	validates :entry_date, presence: true
	validates :expenses, presence: true
	validates :tax, presence: true
	validates :total_cost, presence: true
	validates :promised_date, presence: true

	def order_info
		"Folio: " + id.to_s + ", Fecha inicial: " + (entry_date.strftime('%v')).to_s + ", Fecha promesa: " + (promised_date.strftime('%v')).to_s 
	end
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :order, inverse_of: :procedures
  has_many :labors, inverse_of: :procedure
  has_many :spare_parts, inverse_of: :procedure

  def procedure_name
  	"Folio: " + id.to_s + ", Resumen: " + description
  end
end

app/models/spare_part.rb
class SparePart < ActiveRecord::Base
  belongs_to :procedure, inverse_of: :spare_parts

	validates :name, presence: true
	validates :provider, presence: true
	validates :cost, presence: true
	validates :quantity, presence: true
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :client, inverse_of: :vehicles
  has_many :order_vehicle_workshops, inverse_of: :vehicle

	validates :series_num, presence: true
	validates :model, presence: true
	validates :brand, presence: true
	validates :color, presence: true
	validates :placas, presence: true

  def vehicle_info
    model + " " + brand + " " + placas
  end

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  has_many :order_vehicle_workshops, inverse_of: :workshop

	validates :name, presence: true
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
    @sql = @workshops.to_sql
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @sql = Workshop.where(id: params[:id]).to_sql
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_for(@workshop) do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% @workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit class: "button medium success" %>
  </div>
<% end %>

app/views/workshops/edit.html.erb
<h1>Editing workshop</h1>

<%= render 'form' %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/index.html.erb
<h1>Listing workshops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.name %></td>
        <td><%= workshop.description %></td>
        <td><%= link_to 'Show', workshop %></td>
        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path, class: "button medium success" %>

app/views/workshops/new.html.erb
<h1>New workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workshop.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workshop.description %>
</p>

<%= link_to 'Edit', edit_workshop_path(@workshop) %> |
<%= link_to 'Back', workshops_path %>