config/routes.rb
Rails.application.routes.draw do
  get 'reports/index' => 'reports#index', as: :reports

  get 'reports/employee_on_vehicle/:id' => 'reports#employee_on_vehicle', as: :employee_on_vehicle

  get 'reports/vehicle_workshop/:id' => 'reports#vehicle_workshop', as: :vehicle_workshop

  get 'reports/vehicle_spare_parts/:id' => 'reports#vehicle_spare_parts', as: :vehicle_spare_parts

  get 'reports/vehicle_procedures/:id' => 'reports#vehicle_procedures', as: :vehicle_procedures

  resources :order_vehicle_workshops

  get 'finance/summary' => 'finance#summary', as: :finance

  resources :employees

  resources :workshops

  resources :fiscal_data

  resources :clients

  resources :locations

  resources :spare_parts

  resources :labors

  resources :vehicles

  resources :orders

  resources :procedures

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :vehicles, inverse_of: :client
  belongs_to :location, inverse_of: :client

	validates :first_name, presence: true
	validates :last_name, presence: true

  def full_name
    first_name + " " + last_name + " - Vehiculos: " + vehicles.count.to_s 
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders, inverse_of: :employee
  has_many :labors, inverse_of: :employee

	validates :name, presence: true
	validates :last_name, presence: true
	validates :salary, presence: true

	def full_name
		name + " " + last_name + " - Trabajos: " + orders.count.to_s 
	end

  def full_name_only
    name + " " + middle_name + " " + last_name
  end
end

app/models/fiscal_datum.rb
class FiscalDatum < ActiveRecord::Base
  belongs_to :location, inverse_of: :fiscal_data

	validates :RFC, presence: true
	validates :entity_name, presence: true
	validates :date_of_birth, presence: true

end

app/models/labor.rb
class Labor < ActiveRecord::Base
  belongs_to :employee, inverse_of: :labors
  belongs_to :procedure, inverse_of: :labors

	validates :cost, presence: true
	validates :estimated_time, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :client, inverse_of: :location
  has_one :fiscal_data, inverse_of: :location
  
	validates :street, presence: true
	validates :street_number, presence: true
	validates :suburb, presence: true
	validates :postal_code, presence: true

  def full_address
    street + " " + street_number.to_s + ", " + suburb + " " + postal_code.to_s
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :procedures, inverse_of: :order
  has_many :order_vehicle_workshops, inverse_of: :order
  belongs_to :employee, inverse_of: :orders

	validates :entry_date, presence: true
	validates :expenses, presence: true
	validates :tax, presence: true
	validates :total_cost, presence: true
	validates :promised_date, presence: true

	def order_info
		"Folio: " + id.to_s + ", Fecha inicial: " + (entry_date.strftime('%v')).to_s + ", Fecha promesa: " + (promised_date.strftime('%v')).to_s 
	end
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :order, inverse_of: :procedures
  has_many :labors, inverse_of: :procedure
  has_many :spare_parts, inverse_of: :procedure

  def procedure_name
  	"Folio: " + id.to_s + ", Resumen: " + description
  end
end

app/models/spare_part.rb
class SparePart < ActiveRecord::Base
  belongs_to :procedure, inverse_of: :spare_parts

	validates :name, presence: true
	validates :provider, presence: true
	validates :cost, presence: true
	validates :quantity, presence: true
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :client, inverse_of: :vehicles
  has_many :order_vehicle_workshops, inverse_of: :vehicle

	validates :series_num, presence: true
	validates :model, presence: true
	validates :brand, presence: true
	validates :color, presence: true
	validates :placas, presence: true

  def vehicle_info
    model + " " + brand + " " + placas
  end

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  has_many :order_vehicle_workshops, inverse_of: :workshop

	validates :name, presence: true
end

app/controllers/spare_parts_controller.rb
class SparePartsController < ApplicationController
  before_action :set_spare_part, only: [:show, :edit, :update, :destroy]

  # GET /spare_parts
  # GET /spare_parts.json
  def index
    @spare_parts = SparePart.all
    @sql = @spare_parts.to_sql
  end

  # GET /spare_parts/1
  # GET /spare_parts/1.json
  def show
    @sql = SparePart.where(id: params[:id]).to_sql
  end

  # GET /spare_parts/new
  def new
    @spare_part = SparePart.new
  end

  # GET /spare_parts/1/edit
  def edit
  end

  # POST /spare_parts
  # POST /spare_parts.json
  def create
    @spare_part = SparePart.new(spare_part_params)

    respond_to do |format|
      if @spare_part.save
        format.html { redirect_to @spare_part, notice: 'Spare part was successfully created.' }
        format.json { render :show, status: :created, location: @spare_part }
      else
        format.html { render :new }
        format.json { render json: @spare_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spare_parts/1
  # PATCH/PUT /spare_parts/1.json
  def update
    respond_to do |format|
      if @spare_part.update(spare_part_params)
        format.html { redirect_to @spare_part, notice: 'Spare part was successfully updated.' }
        format.json { render :show, status: :ok, location: @spare_part }
      else
        format.html { render :edit }
        format.json { render json: @spare_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spare_parts/1
  # DELETE /spare_parts/1.json
  def destroy
    @spare_part.destroy
    respond_to do |format|
      format.html { redirect_to spare_parts_url, notice: 'Spare part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spare_part
      @spare_part = SparePart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spare_part_params
      params.require(:spare_part).permit(:name, :provider, :cost, :extra_cost, :quantity)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/spare_parts_helper.rb
module SparePartsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/spare_parts/_form.html.erb
<%= form_for(@spare_part) do |f| %>
  <% if @spare_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spare_part.errors.count, "error") %> prohibited this spare_part from being saved:</h2>

      <ul>
      <% @spare_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :extra_cost %><br>
    <%= f.text_field :extra_cost %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :procedure_id %><br>
    <%= f.collection_select :procedure_id, Procedure.all, :id, :procedure_name %>
  </div>
  <div class="actions">
    <%= f.submit class: "button medium success" %>
  </div>
<% end %>

app/views/spare_parts/edit.html.erb
<h1>Editing spare_part</h1>

<%= render 'form' %>

<%= link_to 'Show', @spare_part %> |
<%= link_to 'Back', spare_parts_path %>

app/views/spare_parts/index.html.erb
<h1>Listing spare_parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Provider</th>
      <th>Cost</th>
      <th>Extra cost</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spare_parts.each do |spare_part| %>
      <tr>
        <td><%= spare_part.name %></td>
        <td><%= spare_part.provider %></td>
        <td><%= spare_part.cost %></td>
        <td><%= spare_part.extra_cost %></td>
        <td><%= spare_part.quantity %></td>
        <td><%= link_to 'Show', spare_part %></td>
        <td><%= link_to 'Edit', edit_spare_part_path(spare_part) %></td>
        <td><%= link_to 'Destroy', spare_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spare part', new_spare_part_path, class: "button medium success" %>

app/views/spare_parts/new.html.erb
<h1>New spare_part</h1>

<%= render 'form' %>

<%= link_to 'Back', spare_parts_path %>

app/views/spare_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spare_part.name %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @spare_part.provider %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @spare_part.cost %>
</p>

<p>
  <strong>Extra cost:</strong>
  <%= @spare_part.extra_cost %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @spare_part.quantity %>
</p>

<%= link_to 'Edit', edit_spare_part_path(@spare_part) %> |
<%= link_to 'Back', spare_parts_path %>