config/routes.rb
Rails.application.routes.draw do
  get 'reports/index' => 'reports#index', as: :reports

  get 'reports/employee_on_vehicle/:id' => 'reports#employee_on_vehicle', as: :employee_on_vehicle

  get 'reports/vehicle_workshop/:id' => 'reports#vehicle_workshop', as: :vehicle_workshop

  get 'reports/vehicle_spare_parts/:id' => 'reports#vehicle_spare_parts', as: :vehicle_spare_parts

  get 'reports/vehicle_procedures/:id' => 'reports#vehicle_procedures', as: :vehicle_procedures

  resources :order_vehicle_workshops

  get 'finance/summary' => 'finance#summary', as: :finance

  resources :employees

  resources :workshops

  resources :fiscal_data

  resources :clients

  resources :locations

  resources :spare_parts

  resources :labors

  resources :vehicles

  resources :orders

  resources :procedures

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :vehicles, inverse_of: :client
  belongs_to :location, inverse_of: :client

	validates :first_name, presence: true
	validates :last_name, presence: true

  def full_name
    first_name + " " + last_name + " - Vehiculos: " + vehicles.count.to_s 
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders, inverse_of: :employee
  has_many :labors, inverse_of: :employee

	validates :name, presence: true
	validates :last_name, presence: true
	validates :salary, presence: true

	def full_name
		name + " " + last_name + " - Trabajos: " + orders.count.to_s 
	end

  def full_name_only
    name + " " + middle_name + " " + last_name
  end
end

app/models/fiscal_datum.rb
class FiscalDatum < ActiveRecord::Base
  belongs_to :location, inverse_of: :fiscal_data

	validates :RFC, presence: true
	validates :entity_name, presence: true
	validates :date_of_birth, presence: true

end

app/models/labor.rb
class Labor < ActiveRecord::Base
  belongs_to :employee, inverse_of: :labors
  belongs_to :procedure, inverse_of: :labors

	validates :cost, presence: true
	validates :estimated_time, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :client, inverse_of: :location
  has_one :fiscal_data, inverse_of: :location
  
	validates :street, presence: true
	validates :street_number, presence: true
	validates :suburb, presence: true
	validates :postal_code, presence: true

  def full_address
    street + " " + street_number.to_s + ", " + suburb + " " + postal_code.to_s
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :procedures, inverse_of: :order
  has_many :order_vehicle_workshops, inverse_of: :order
  belongs_to :employee, inverse_of: :orders

	validates :entry_date, presence: true
	validates :expenses, presence: true
	validates :tax, presence: true
	validates :total_cost, presence: true
	validates :promised_date, presence: true

	def order_info
		"Folio: " + id.to_s + ", Fecha inicial: " + (entry_date.strftime('%v')).to_s + ", Fecha promesa: " + (promised_date.strftime('%v')).to_s 
	end
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :order, inverse_of: :procedures
  has_many :labors, inverse_of: :procedure
  has_many :spare_parts, inverse_of: :procedure

  def procedure_name
  	"Folio: " + id.to_s + ", Resumen: " + description
  end
end

app/models/spare_part.rb
class SparePart < ActiveRecord::Base
  belongs_to :procedure, inverse_of: :spare_parts

	validates :name, presence: true
	validates :provider, presence: true
	validates :cost, presence: true
	validates :quantity, presence: true
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :client, inverse_of: :vehicles
  has_many :order_vehicle_workshops, inverse_of: :vehicle

	validates :series_num, presence: true
	validates :model, presence: true
	validates :brand, presence: true
	validates :color, presence: true
	validates :placas, presence: true

  def vehicle_info
    model + " " + brand + " " + placas
  end

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  has_many :order_vehicle_workshops, inverse_of: :workshop

	validates :name, presence: true
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]

  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.all
    @sql = @procedures.to_sql
  end

  # GET /procedures/1
  # GET /procedures/1.json
  def show
    @sql = Procedure.where(id: params[:id]).to_sql
  end

  # GET /procedures/new
  def new
    @procedure = Procedure.new
  end

  # GET /procedures/1/edit
  def edit
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @procedure = Procedure.new(procedure_params)

    respond_to do |format|
      if @procedure.save
        format.html { redirect_to @procedure, notice: 'Procedure was successfully created.' }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: 'Procedure was successfully updated.' }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    @procedure.destroy
    respond_to do |format|
      format.html { redirect_to procedures_url, notice: 'Procedure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:description, :consumible_lab, :consumible_general)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/procedures/_form.html.erb
<%= form_for(@procedure) do |f| %>
  <% if @procedure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>

      <ul>
      <% @procedure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :consumible_lab %><br>
    <%= f.text_field :consumible_lab %>
  </div>
  <div class="field">
    <%= f.label :consumible_general %><br>
    <%= f.text_field :consumible_general %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.collection_select :order_id, Order.all, :id, :order_info %>
  </div>
  <div class="actions">
    <%= f.submit class: "button medium success" %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<h1>Editing procedure</h1>

<%= render 'form' %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<h1>Listado de procedimientos</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Consumible lab</th>
      <th>Consumible general</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.description %></td>
        <td><%= procedure.consumible_lab %></td>
        <td><%= procedure.consumible_general %></td>
        <td><%= link_to 'Show', procedure %></td>
        <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
        <td><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Procedure', new_procedure_path, class: "button medium success" %>

app/views/procedures/new.html.erb
<h1>New procedure</h1>

<%= render 'form' %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @procedure.description %>
</p>

<p>
  <strong>Consumible lab:</strong>
  <%= @procedure.consumible_lab %>
</p>

<p>
  <strong>Consumible general:</strong>
  <%= @procedure.consumible_general %>
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> |
<%= link_to 'Back', procedures_path %>