config/routes.rb
Rails.application.routes.draw do
  get 'reports/index' => 'reports#index', as: :reports

  get 'reports/employee_on_vehicle/:id' => 'reports#employee_on_vehicle', as: :employee_on_vehicle

  get 'reports/vehicle_workshop/:id' => 'reports#vehicle_workshop', as: :vehicle_workshop

  get 'reports/vehicle_spare_parts/:id' => 'reports#vehicle_spare_parts', as: :vehicle_spare_parts

  get 'reports/vehicle_procedures/:id' => 'reports#vehicle_procedures', as: :vehicle_procedures

  resources :order_vehicle_workshops

  get 'finance/summary' => 'finance#summary', as: :finance

  resources :employees

  resources :workshops

  resources :fiscal_data

  resources :clients

  resources :locations

  resources :spare_parts

  resources :labors

  resources :vehicles

  resources :orders

  resources :procedures

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :vehicles, inverse_of: :client
  belongs_to :location, inverse_of: :client

	validates :first_name, presence: true
	validates :last_name, presence: true

  def full_name
    first_name + " " + last_name + " - Vehiculos: " + vehicles.count.to_s 
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders, inverse_of: :employee
  has_many :labors, inverse_of: :employee

	validates :name, presence: true
	validates :last_name, presence: true
	validates :salary, presence: true

	def full_name
		name + " " + last_name + " - Trabajos: " + orders.count.to_s 
	end

  def full_name_only
    name + " " + middle_name + " " + last_name
  end
end

app/models/fiscal_datum.rb
class FiscalDatum < ActiveRecord::Base
  belongs_to :location, inverse_of: :fiscal_data

	validates :RFC, presence: true
	validates :entity_name, presence: true
	validates :date_of_birth, presence: true

end

app/models/labor.rb
class Labor < ActiveRecord::Base
  belongs_to :employee, inverse_of: :labors
  belongs_to :procedure, inverse_of: :labors

	validates :cost, presence: true
	validates :estimated_time, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :client, inverse_of: :location
  has_one :fiscal_data, inverse_of: :location
  
	validates :street, presence: true
	validates :street_number, presence: true
	validates :suburb, presence: true
	validates :postal_code, presence: true

  def full_address
    street + " " + street_number.to_s + ", " + suburb + " " + postal_code.to_s
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :procedures, inverse_of: :order
  has_many :order_vehicle_workshops, inverse_of: :order
  belongs_to :employee, inverse_of: :orders

	validates :entry_date, presence: true
	validates :expenses, presence: true
	validates :tax, presence: true
	validates :total_cost, presence: true
	validates :promised_date, presence: true

	def order_info
		"Folio: " + id.to_s + ", Fecha inicial: " + (entry_date.strftime('%v')).to_s + ", Fecha promesa: " + (promised_date.strftime('%v')).to_s 
	end
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :order, inverse_of: :procedures
  has_many :labors, inverse_of: :procedure
  has_many :spare_parts, inverse_of: :procedure

  def procedure_name
  	"Folio: " + id.to_s + ", Resumen: " + description
  end
end

app/models/spare_part.rb
class SparePart < ActiveRecord::Base
  belongs_to :procedure, inverse_of: :spare_parts

	validates :name, presence: true
	validates :provider, presence: true
	validates :cost, presence: true
	validates :quantity, presence: true
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :client, inverse_of: :vehicles
  has_many :order_vehicle_workshops, inverse_of: :vehicle

	validates :series_num, presence: true
	validates :model, presence: true
	validates :brand, presence: true
	validates :color, presence: true
	validates :placas, presence: true

  def vehicle_info
    model + " " + brand + " " + placas
  end

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  has_many :order_vehicle_workshops, inverse_of: :workshop

	validates :name, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    
  end

  def employee_on_vehicle
    @vehicle = Vehicle.find(params[:id])
    @sql = Vehicle.where(id: params[:id]).to_sql
  end

  def vehicle_workshop
    @vehicle = Vehicle.find(params[:id])
    @sql = Vehicle.where(id: params[:id]).to_sql
  end

  def vehicle_spare_parts
  end

  def vehicle_procedures
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/finance_helper.rb
module FinanceHelper
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/reports/employee_on_vehicle.html.erb
<h2>Employees that worked on <%= @vehicle.vehicle_info %></h2>
<hr>
<ul>
<style>
  a:hover {
    color: #43ac6a;
  }
</style>
<% @vehicle.order_vehicle_workshops.each do |v| %>
  <% if v.order.employee %>
    <a href="<%= employee_path(v.order.employee) %>">
      <li style="font-size:30px;margin-bottom: 25px;">
        <%= v.order.employee.full_name_only %>
      </li>      
    </a>
  <% end %>
<% end %>  
</ul>

app/views/reports/index.html.erb
<h1>Reportes</h1>

<style>
  table a:visited {
    color: white !important;
  }
</style>

<table>
  <thead>
    <th>Query</th>
    <th>Select</th>
    <th>Go</th>
  </thead>
  <tbody>

    <tr>
      <td>Workshops of Vehicle:</td>
      <td>
        <%= collection_select :get, :vehicle_id, Vehicle.all, :id, :vehicle_info %>
      </td>
      <td>
        <%= link_to "GO", vehicle_workshop_path(1), class: "button tiny", id: "JAJAJA" %>
      </td>
    </tr>

    <tr>
      <td>Employees that worked on Vehicle:</td>
      <td>
        <%= collection_select :get, :vehicle_id, Vehicle.all, :id, :vehicle_info %>
      </td>
      <td>
        <%= link_to "GO", employee_on_vehicle_path(1), class: "button tiny", id: "JAJAJA" %>
      </td>
    </tr>

    <tr>
      <td>Procedures of Vehicle:</td>
      <td>
        <%= collection_select :get, :vehicle_id, Vehicle.all, :id, :vehicle_info %>
      </td>
      <td>
        <%= link_to "GO", root_path, class: "button tiny", id: "JAJAJA" %>
      </td>
    </tr>

  </tbody>
</table>

app/views/reports/vehicle_procedures.html.erb
<h1>Reports#vehicle_procedures</h1>
<p>Find me in app/views/reports/vehicle_procedures.html.erb</p>

app/views/reports/vehicle_spare_parts.html.erb
<h1>Reports#vehicle_spare_parts</h1>
<p>Find me in app/views/reports/vehicle_spare_parts.html.erb</p>

app/views/reports/vehicle_workshop.html.erb
<h2>Workshops for <%= @vehicle.vehicle_info %></h2>
<hr>
<ul>
<style>
  a:hover {
    background-color: transparent;
    color: #43ac6a;
  }
</style>
<% @vehicle.order_vehicle_workshops.each do |v| %>
  <li style="font-size:30px;margin-bottom: 25px;">
    <a href="<%= workshop_path(v.workshop) %>">
      <%= v.workshop.name %>
    </a>
  </li>
<% end %>  
</ul>